sonar.projectKey=maverick0322_ReflectAI
sonar.organization=maverick0322
sonar.projectName=ReflectAI
sonar.projectVersion=1.0

sonar.sources=reflectai/src
sonar.exclusions=reflectai/node_modules/**, reflectai/.next/**, reflectai/public/**, docs/**, **/*.adoc, **/*.test.ts, **/*.test.tsx

sonar.tests=reflectai/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=reflectai/coverage/lcov.info

sonar.sourceEncoding=UTF-8