export const apiMessages = {
  common: {
    invalidData: 'Datos invalidos',
    unauthorized: 'No autorizado',
    forbiddenOrigin: 'Origen no permitido',
    tooManyRequests:
      'Demasiados intentos. Espera unos minutos antes de continuar.',
  },
  auth: {
    loginSucceeded: 'Sesion iniciada correctamente',
    loginFailed: 'No se pudo iniciar sesion con las credenciales proporcionadas.',
    loginUnexpected: 'Error inesperado al iniciar sesion',
    invalidRegisterData: 'Datos de registro invalidos',
    registerSucceeded: 'Usuario registrado correctamente',
    registerFailed: 'No se pudo completar el registro.',
    registerDuplicateEmail: 'Ya existe una cuenta con ese correo.',
    registerRateLimited:
      'Se hicieron demasiados intentos. Espera unos minutos antes de crear otra cuenta.',
    registerInvalidRedirectUrl: 'La URL de confirmacion no esta permitida en Supabase.',
    registerUnexpected: 'Error inesperado al registrar usuario',
    recoverLinkSent: 'Enlace de recuperacion enviado',
    recoverFailed: 'No se pudo enviar el enlace de recuperacion',
    recoverRateLimited:
      'Se hicieron demasiados intentos. Espera unos minutos antes de pedir otro enlace.',
    recoverEmailDeliveryFailed: [
      'Supabase no pudo enviar el correo de recuperacion.',
      'Revisa la configuracion SMTP o intenta con otro correo.',
    ].join(' '),
    recoverUnexpected: 'Error inesperado al recuperar contrasena',
    confirmRecoverySucceeded: 'Recuperacion confirmada',
    confirmRecoveryFailed: 'No se pudo confirmar la recuperacion',
    confirmRecoveryUnexpected: 'Error inesperado al confirmar recuperacion',
    passwordCurrentValidationFailed: 'No se pudo validar la contrasena actual',
    passwordCurrentIncorrect: 'La contrasena actual es incorrecta',
    passwordRecoverySessionInvalid:
      'La sesion de recuperacion no es valida o expiro. Solicita un nuevo enlace.',
    passwordMustDiffer: 'La nueva contrasena debe ser diferente a la actual.',
    passwordUpdated: 'Contrasena actualizada correctamente',
    passwordUpdateFailed: 'No se pudo actualizar la contrasena',
    passwordUpdateUnexpected: 'Error inesperado al actualizar contrasena',
    passwordVerified: 'Contrasena actual validada correctamente',
    passwordVerifyUnexpected: 'Error inesperado al validar la contrasena actual',
    deleteAccountFailed: [
      'No se pudo eliminar la cuenta.',
      'Revisa las relaciones en cascada de profiles y reflection_sessions.',
    ].join(' '),
    deleteAccountSucceeded: 'Cuenta eliminada correctamente',
    deleteAccountUnexpected: 'Error inesperado al eliminar cuenta',
    logoutSucceeded: 'Sesion cerrada correctamente',
    logoutUnexpected: 'Error inesperado al cerrar sesion',
  },
  profile: {
    fetchSucceeded: 'Perfil obtenido correctamente',
    fetchFailed: 'No se pudo obtener el perfil',
    fetchUnexpected: 'Error inesperado al obtener perfil',
    createFailed: 'No se pudo crear el perfil',
    updateSucceeded: 'Perfil actualizado correctamente',
    updateFailed: 'No se pudo actualizar el perfil',
    updateUnexpected: 'Error inesperado al actualizar perfil',
    avatarRequired: 'La foto de perfil es obligatoria',
    avatarInvalidType: 'Solo se permiten formatos JPG, PNG o WEBP',
    avatarTooLarge: 'La imagen debe pesar menos de 2MB',
    avatarInvalidSignature:
      'El contenido de la imagen no coincide con el formato permitido',
    avatarUploadFailed: [
      'No se pudo subir la foto.',
      'Verifica que exista el bucket profile-avatars en Supabase Storage.',
    ].join(' '),
    avatarUpdateFailed: 'No se pudo actualizar la foto de perfil',
    avatarUpdateSucceeded: 'Foto de perfil actualizada correctamente',
    avatarUnexpected: 'Error inesperado al subir la foto de perfil',
  },
  ai: {
    invalidAnalyzeSessionData: 'Datos invalidos',
    invalidNextQuestionData: 'Datos invalidos',
    sessionNotFound: 'Sesion no encontrada',
    analyzeSucceeded: 'Analisis generado correctamente',
    analyzeFailed: 'No se pudo guardar el analisis',
    analyzeUnexpected: 'Error inesperado al generar analisis',
    dailyQuoteSucceeded: 'Cita generada correctamente',
    dailyQuoteFallbackSucceeded: 'Cita local generada correctamente',
    dailyQuoteUnexpected: 'Error inesperado al generar cita',
    nextQuestionDone: 'No hay mas preguntas',
    nextQuestionUnexpected: 'Error inesperado al generar pregunta',
  },
  reflection: {
    createSucceeded: 'Sesion creada correctamente',
    createFailed: 'No se pudo crear la sesion',
    createUnexpected: 'Error inesperado al crear sesion',
    listSucceeded: 'Sesiones obtenidas correctamente',
    listFailed: 'No se pudo obtener el historial',
    listUnexpected: 'Error inesperado al obtener sesiones',
    detailSucceeded: 'Sesion obtenida correctamente',
    detailFailed: 'Sesion no encontrada',
    detailUnexpected: 'Error inesperado al obtener la sesion',
    responseSucceeded: 'Respuesta guardada correctamente',
    responseFailed: 'No se pudo guardar la respuesta',
    responseUnexpected: 'Error inesperado al guardar la respuesta',
    responseAlreadyCompleted:
      'No se pueden agregar respuestas a una sesion completada',
    completeSucceeded: 'Sesion completada correctamente',
    completeFailed: 'No se pudo completar la sesion',
    completeUnexpected: 'Error inesperado al completar la sesion',
    completeAlreadyCompleted: 'La sesion ya esta completada',
    completeMissingResponses:
      'No se puede completar una sesion sin respuestas',
  },
} as const;
